import { db } from './firebase/config.js';
import { doc, setDoc, serverTimestamp } from 'firebase/firestore';

const users = [
  {
    //강남
    id: 'prf_gangnam_1',
    data: {
      uid: 'prf_gangnam_1',
      userId: 'gangnam_prf1',
      password: '1234',
      name: '박성훈',
      phone: '010-1111-2222',
      email: 'sunghoon@gmail.com',
      birthDate: '1988-03-15',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_gangnam',
      career: ['국내 대회 우승', '클라이밍 강사 8년'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EB%B0%95%EC%84%B1%ED%9B%88.jpg?alt=media&token=4c04a6e5-82a6-4850-b0ee-22d53b1ff2c5',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_gangnam_2',
    data: {
      uid: 'prf_gangnam_2',
      userId: 'gangnam_prf2',
      password: '1234',
      name: '이수진',
      phone: '010-2222-3333',
      email: 'soojin@gmail.com',
      birthDate: '1993-07-22',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_gangnam',
      career: ['클라이밍 강사 6년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%9D%B4%EC%88%98%EC%A7%84.jpg?alt=media&token=b1d770e8-1cdc-436e-a8dc-8a48bdf80f9f',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_gangnam_3',
    data: {
      uid: 'prf_gangnam_3',
      userId: 'gangnam_prf3',
      password: '1234',
      name: '박지은',
      phone: '010-3333-4444',
      email: 'jieun@gmail.com',
      birthDate: '1997-11-03',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_gangnam',
      career: ['클라이밍 강사 2년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EB%B0%95%EC%A7%80%EC%9D%80.jpg?alt=media&token=7ce9b81e-5df7-4a2b-a9a6-a6fc0306885e',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  //일산점
  {
    id: 'prf_ilsan_1',
    data: {
      uid: 'prf_ilsan_1',
      userId: 'ilsan_prf1',
      password: '1234',
      name: '최현우',
      phone: '010-5555-1111',
      email: 'hyunwoo@gmail.com',
      birthDate: '1989-04-11',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_ilsan',
      career: ['국내 대회 입상', '클라이밍 강사 7년'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%B5%9C%ED%98%84%EC%9A%B0.jpg?alt=media&token=b7ac4da0-47a5-49b6-b295-bd4c38952c63',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  //
  {
    id: 'prf_ilsan_2',
    data: {
      uid: 'prf_ilsan_2',
      userId: 'ilsan_prf2',
      password: '1234',
      name: '정우진',
      phone: '010-5555-2222',
      email: 'woojin@gmail.com',
      birthDate: '1992-09-18',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_ilsan',
      career: ['클라이밍 강사 5년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%A0%95%EC%9A%B0%EC%A7%84.jpg?alt=media&token=8e67253b-6304-465c-9796-cfd803bd25b1',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_ilsan_3',
    data: {
      uid: 'prf_ilsan_3',
      userId: 'ilsan_prf3',
      password: '1234',
      name: '최유진',
      phone: '010-5555-3333',
      email: 'yujin@gmail.com',
      birthDate: '1996-12-05',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_ilsan',
      career: ['클라이밍 강사 2년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%B5%9C%EC%9C%A0%EC%A7%84.jpg?alt=media&token=c08ead8e-04a8-4cd8-bb3a-287efa22f8d8',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  // 이수점
  {
    id: 'prf_isu_1',
    data: {
      uid: 'prf_isu_1',
      userId: 'isu_prf1',
      password: '1234',
      name: '김준호',
      phone: '010-6666-1111',
      email: 'isu1@gmail.com',
      birthDate: '1990-05-12',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_isu',
      career: ['국가대표 출신', '볼더링 대회 1위'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EA%B9%80%EC%A4%80%ED%98%B8.jpg?alt=media&token=c4a6d639-4b53-429b-a1a9-92d1751a90ae',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_isu_2',
    data: {
      uid: 'prf_isu_2',
      userId: 'isu_prf2',
      password: '1234',
      name: '김서연',
      phone: '010-6666-2222',
      email: 'isu2@gmail.com',
      birthDate: '1995-08-21',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_isu',
      career: ['실내 클라이밍 강사 5년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EA%B9%80%EC%84%9C%EC%97%B0.jpg?alt=media&token=2b44a5ab-aaf2-4b01-ba91-abb35731d960',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_isu_3',
    data: {
      uid: 'prf_isu_3',
      userId: 'isu_prf3',
      password: '1234',
      name: '이민수',
      phone: '010-6666-3333',
      email: 'isu3@gmail.com',
      birthDate: '1998-02-10',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_isu',
      career: ['클라이밍 강사 3년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%9D%B4%EB%AF%BC%EC%88%98.jpg?alt=media&token=979043fb-c722-4d35-8de7-4898c091bbd7',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  //마곡점
  {
    id: 'prf_magok_1',
    data: {
      uid: 'prf_magok_1',
      userId: 'magok_prf1',
      password: '1234',
      name: '박성훈',
      phone: '010-7777-1111',
      email: 'magok1@gmail.com',
      birthDate: '1988-03-15',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_magok',
      career: ['국내 대회 우승', '클라이밍 강사 8년'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EB%B0%95%EC%84%B1%ED%9B%88.jpg?alt=media&token=4c04a6e5-82a6-4850-b0ee-22d53b1ff2c5',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_magok_2',
    data: {
      uid: 'prf_magok_2',
      userId: 'magok_prf2',
      password: '1234',
      name: '이수진',
      phone: '010-7777-2222',
      email: 'magok2@gmail.com',
      birthDate: '1993-07-22',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_magok',
      career: ['클라이밍 강사 6년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%9D%B4%EC%88%98%EC%A7%84.jpg?alt=media&token=b1d770e8-1cdc-436e-a8dc-8a48bdf80f9f',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_magok_3',
    data: {
      uid: 'prf_magok_3',
      userId: 'magok_prf3',
      password: '1234',
      name: '박지은',
      phone: '010-7777-3333',
      email: 'magok3@gmail.com',
      birthDate: '1997-11-03',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_magok',
      career: ['클라이밍 강사 2년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EB%B0%95%EC%A7%80%EC%9D%80.jpg?alt=media&token=7ce9b81e-5df7-4a2b-a9a6-a6fc0306885e',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  // 문래점
  {
    id: 'prf_mullae_1',
    data: {
      uid: 'prf_mullae_1',
      userId: 'mullae_prf1',
      password: '1234',
      name: '최현우',
      phone: '010-8888-1111',
      email: 'mullae1@gmail.com',
      birthDate: '1989-04-11',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_mullae',
      career: ['국내 대회 입상', '클라이밍 강사 7년'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%B5%9C%ED%98%84%EC%9A%B0.jpg?alt=media&token=b7ac4da0-47a5-49b6-b295-bd4c38952c63',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_mullae_2',
    data: {
      uid: 'prf_mullae_2',
      userId: 'mullae_prf2',
      password: '1234',
      name: '정우진',
      phone: '010-8888-2222',
      email: 'mullae2@gmail.com',
      birthDate: '1992-09-18',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_mullae',
      career: ['클라이밍 강사 5년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%A0%95%EC%9A%B0%EC%A7%84.jpg?alt=media&token=8e67253b-6304-465c-9796-cfd803bd25b1',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_mullae_3',
    data: {
      uid: 'prf_mullae_3',
      userId: 'mullae_prf3',
      password: '1234',
      name: '최유진',
      phone: '010-8888-3333',
      email: 'mullae3@gmail.com',
      birthDate: '1996-12-05',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_mullae',
      career: ['클라이밍 강사 2년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%B5%9C%EC%9C%A0%EC%A7%84.jpg?alt=media&token=c08ead8e-04a8-4cd8-bb3a-287efa22f8d8',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  // 논현점
  {
    id: 'prf_nonhyeon_1',
    data: {
      uid: 'prf_nonhyeon_1',
      userId: 'nonhyeon_prf1',
      password: '1234',
      name: '김준호',
      phone: '010-9999-1111',
      email: 'nonhyeon1@gmail.com',
      birthDate: '1990-05-12',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_nonhyeon',
      career: ['국가대표 출신', '볼더링 대회 1위'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EA%B9%80%EC%A4%80%ED%98%B8.jpg?alt=media&token=c4a6d639-4b53-429b-a1a9-92d1751a90ae',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_nonhyeon_2',
    data: {
      uid: 'prf_nonhyeon_2',
      userId: 'nonhyeon_prf2',
      password: '1234',
      name: '김서연',
      phone: '010-9999-2222',
      email: 'nonhyeon2@gmail.com',
      birthDate: '1995-08-21',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_nonhyeon',
      career: ['실내 클라이밍 강사 5년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EA%B9%80%EC%84%9C%EC%97%B0.jpg?alt=media&token=2b44a5ab-aaf2-4b01-ba91-abb35731d960',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_nonhyeon_3',
    data: {
      uid: 'prf_nonhyeon_3',
      userId: 'nonhyeon_prf3',
      password: '1234',
      name: '이민수',
      phone: '010-9999-3333',
      email: 'nonhyeon3@gmail.com',
      birthDate: '1998-02-10',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_nonhyeon',
      career: ['클라이밍 강사 3년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%9D%B4%EB%AF%BC%EC%88%98.jpg?alt=media&token=979043fb-c722-4d35-8de7-4898c091bbd7',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  // 사당점
  {
    id: 'prf_sadang_1',
    data: {
      uid: 'prf_sadang_1',
      userId: 'sadang_prf1',
      password: '1234',
      name: '박성훈',
      phone: '010-1212-1111',
      email: 'sadang1@gmail.com',
      birthDate: '1988-03-15',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_sadang',
      career: ['국내 대회 우승', '클라이밍 강사 8년'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EB%B0%95%EC%84%B1%ED%9B%88.jpg?alt=media&token=4c04a6e5-82a6-4850-b0ee-22d53b1ff2c5',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_sadang_2',
    data: {
      uid: 'prf_sadang_2',
      userId: 'sadang_prf2',
      password: '1234',
      name: '이수진',
      phone: '010-1212-2222',
      email: 'sadang2@gmail.com',
      birthDate: '1993-07-22',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_sadang',
      career: ['클라이밍 강사 6년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%9D%B4%EC%88%98%EC%A7%84.jpg?alt=media&token=b1d770e8-1cdc-436e-a8dc-8a48bdf80f9f',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_sadang_3',
    data: {
      uid: 'prf_sadang_3',
      userId: 'sadang_prf3',
      password: '1234',
      name: '박지은',
      phone: '010-1212-3333',
      email: 'sadang3@gmail.com',
      birthDate: '1997-11-03',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_sadang',
      career: ['클라이밍 강사 2년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EB%B0%95%EC%A7%80%EC%9D%80.jpg?alt=media&token=7ce9b81e-5df7-4a2b-a9a6-a6fc0306885e',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  // 성수점
  {
    id: 'prf_seongsu_1',
    data: {
      uid: 'prf_seongsu_1',
      userId: 'seongsu_prf1',
      password: '1234',
      name: '최현우',
      phone: '010-3434-1111',
      email: 'seongsu1@gmail.com',
      birthDate: '1989-04-11',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_seongsu',
      career: ['국내 대회 입상', '클라이밍 강사 7년'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%B5%9C%ED%98%84%EC%9A%B0.jpg?alt=media&token=b7ac4da0-47a5-49b6-b295-bd4c38952c63',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_seongsu_2',
    data: {
      uid: 'prf_seongsu_2',
      userId: 'seongsu_prf2',
      password: '1234',
      name: '정우진',
      phone: '010-3434-2222',
      email: 'seongsu2@gmail.com',
      birthDate: '1992-09-18',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_seongsu',
      career: ['클라이밍 강사 5년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%A0%95%EC%9A%B0%EC%A7%84.jpg?alt=media&token=8e67253b-6304-465c-9796-cfd803bd25b1',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_seongsu_3',
    data: {
      uid: 'prf_seongsu_3',
      userId: 'seongsu_prf3',
      password: '1234',
      name: '최유진',
      phone: '010-3434-3333',
      email: 'seongsu3@gmail.com',
      birthDate: '1996-12-05',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_seongsu',
      career: ['클라이밍 강사 2년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%B5%9C%EC%9C%A0%EC%A7%84.jpg?alt=media&token=c08ead8e-04a8-4cd8-bb3a-287efa22f8d8',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  // 신림점
  {
    id: 'prf_sillim_1',
    data: {
      uid: 'prf_sillim_1',
      userId: 'sillim_prf1',
      password: '1234',
      name: '김준호',
      phone: '010-5656-1111',
      email: 'sillim1@gmail.com',
      birthDate: '1990-05-12',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_sillim',
      career: ['국가대표 출신', '볼더링 대회 1위'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EA%B9%80%EC%A4%80%ED%98%B8.jpg?alt=media&token=c4a6d639-4b53-429b-a1a9-92d1751a90ae',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_sillim_2',
    data: {
      uid: 'prf_sillim_2',
      userId: 'sillim_prf2',
      password: '1234',
      name: '김서연',
      phone: '010-5656-2222',
      email: 'sillim2@gmail.com',
      birthDate: '1995-08-21',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_sillim',
      career: ['실내 클라이밍 강사 5년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EA%B9%80%EC%84%9C%EC%97%B0.jpg?alt=media&token=2b44a5ab-aaf2-4b01-ba91-abb35731d960',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_sillim_3',
    data: {
      uid: 'prf_sillim_3',
      userId: 'sillim_prf3',
      password: '1234',
      name: '이민수',
      phone: '010-5656-3333',
      email: 'sillim3@gmail.com',
      birthDate: '1998-02-10',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_sillim',
      career: ['클라이밍 강사 3년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%9D%B4%EB%AF%BC%EC%88%98.jpg?alt=media&token=979043fb-c722-4d35-8de7-4898c091bbd7',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  // 신사점
  {
    id: 'prf_sinsa_1',
    data: {
      uid: 'prf_sinsa_1',
      userId: 'sinsa_prf1',
      password: '1234',
      name: '박성훈',
      phone: '010-7878-1111',
      email: 'sinsa1@gmail.com',
      birthDate: '1988-03-15',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_sinsa',
      career: ['국내 대회 우승', '클라이밍 강사 8년'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EB%B0%95%EC%84%B1%ED%9B%88.jpg?alt=media&token=4c04a6e5-82a6-4850-b0ee-22d53b1ff2c5',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_sinsa_2',
    data: {
      uid: 'prf_sinsa_2',
      userId: 'sinsa_prf2',
      password: '1234',
      name: '이수진',
      phone: '010-7878-2222',
      email: 'sinsa2@gmail.com',
      birthDate: '1993-07-22',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_sinsa',
      career: ['클라이밍 강사 6년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%9D%B4%EC%88%98%EC%A7%84.jpg?alt=media&token=b1d770e8-1cdc-436e-a8dc-8a48bdf80f9f',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_sinsa_3',
    data: {
      uid: 'prf_sinsa_3',
      userId: 'sinsa_prf3',
      password: '1234',
      name: '박지은',
      phone: '010-7878-3333',
      email: 'sinsa3@gmail.com',
      birthDate: '1997-11-03',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_sinsa',
      career: ['클라이밍 강사 2년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EB%B0%95%EC%A7%80%EC%9D%80.jpg?alt=media&token=7ce9b81e-5df7-4a2b-a9a6-a6fc0306885e',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  // 양재점
  {
    id: 'prf_yangjae_1',
    data: {
      uid: 'prf_yangjae_1',
      userId: 'yangjae_prf1',
      password: '1234',
      name: '최현우',
      phone: '010-9090-1111',
      email: 'yangjae1@gmail.com',
      birthDate: '1989-04-11',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_yangjae',
      career: ['국내 대회 입상', '클라이밍 강사 7년'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%B5%9C%ED%98%84%EC%9A%B0.jpg?alt=media&token=b7ac4da0-47a5-49b6-b295-bd4c38952c63',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_yangjae_2',
    data: {
      uid: 'prf_yangjae_2',
      userId: 'yangjae_prf2',
      password: '1234',
      name: '정우진',
      phone: '010-9090-2222',
      email: 'yangjae2@gmail.com',
      birthDate: '1992-09-18',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_yangjae',
      career: ['클라이밍 강사 5년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%A0%95%EC%9A%B0%EC%A7%84.jpg?alt=media&token=8e67253b-6304-465c-9796-cfd803bd25b1',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_yangjae_3',
    data: {
      uid: 'prf_yangjae_3',
      userId: 'yangjae_prf3',
      password: '1234',
      name: '최유진',
      phone: '010-9090-3333',
      email: 'yangjae3@gmail.com',
      birthDate: '1996-12-05',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_yangjae',
      career: ['클라이밍 강사 2년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%B5%9C%EC%9C%A0%EC%A7%84.jpg?alt=media&token=c08ead8e-04a8-4cd8-bb3a-287efa22f8d8',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  // 연남점
  {
    id: 'prf_yeonnam_1',
    data: {
      uid: 'prf_yeonnam_1',
      userId: 'yeonnam_prf1',
      password: '1234',
      name: '김준호',
      phone: '010-2323-1111',
      email: 'yeonnam1@gmail.com',
      birthDate: '1990-05-12',
      role: 'professor',
      level: 'V8',
      branchId: 'theclimb_yeonnam',
      career: ['국가대표 출신', '볼더링 대회 1위'],
      qualifications: ['클라이밍 지도자 1급'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EA%B9%80%EC%A4%80%ED%98%B8.jpg?alt=media&token=c4a6d639-4b53-429b-a1a9-92d1751a90ae',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_yeonnam_2',
    data: {
      uid: 'prf_yeonnam_2',
      userId: 'yeonnam_prf2',
      password: '1234',
      name: '김서연',
      phone: '010-2323-2222',
      email: 'yeonnam2@gmail.com',
      birthDate: '1995-08-21',
      role: 'professor',
      level: 'V7',
      branchId: 'theclimb_yeonnam',
      career: ['실내 클라이밍 강사 5년'],
      qualifications: ['생활체육 지도자'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EA%B9%80%EC%84%9C%EC%97%B0.jpg?alt=media&token=2b44a5ab-aaf2-4b01-ba91-abb35731d960',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
  {
    id: 'prf_yeonnam_3',
    data: {
      uid: 'prf_yeonnam_3',
      userId: 'yeonnam_prf3',
      password: '1234',
      name: '이민수',
      phone: '010-2323-3333',
      email: 'yeonnam3@gmail.com',
      birthDate: '1998-02-10',
      role: 'professor',
      level: 'V6',
      branchId: 'theclimb_yeonnam',
      career: ['클라이밍 강사 3년'],
      qualifications: ['클라이밍 수료증'],
      isApproved: true,
      profileImg:
        'https://firebasestorage.googleapis.com/v0/b/catchclimbing-18fe9.firebasestorage.app/o/%EC%9D%B4%EB%AF%BC%EC%88%98.jpg?alt=media&token=979043fb-c722-4d35-8de7-4898c091bbd7',
      autoLogin: false,
      createdAt: serverTimestamp(),
    },
  },
];

async function seed() {
  for (const user of users) {
    await setDoc(doc(db, 'users', user.id), user.data);
  }
  console.log('🔥 전부 업로드 완료');
}

seed();
